// ─── candles.js ───────────────────────────────────────────────────────────────
// Alle Kerzenmuster-Daten für das Quiz.
// Willst du ein neues Quiz bauen (z.B. Chartmuster)?
// → Kopiere diese Datei, ersetze den Inhalt, importiere sie in App.jsx.

import React from "react";

const SVG_SCALE = 0.85;

// ─── Kerzenmuster-Daten ───────────────────────────────────────────────────────
export const candles = [
  {
    name: "Hammer",
    deName: "Hammer",
    merk: "Abverkauf wird gekauft – Käufer übernehmen.",
    color: "green",
    typ: "Bullish Reversal",
    markt: "Abwärtstrend",
    erklaerung: "Hammer signalisiert nach Abwärtstrend eine Abwehr der Verkäufer. Lange Lunte unten = Kaufdruck kommt zurück. Gute Bestätigung: grüne Folgekerze + Volumen.",
    psychologie: "Verkäufer in Panik, Käufer übernehmen.",
    intraday: "Zu Beginn dominieren die Verkäufer und drücken den Kurs tiefer. Im Verlauf werden die Tiefs aggressiv gekauft, der Kurs erholt sich deutlich vom Tagestief.",
    beschreibung: "Kleiner Körper, langer unterer Schatten.",
    bedeutung: "Käufer drehen den Markt – Bodenbildung.",
    bestaetigung: "Grüne Folgekerze, RSI steigt, Volumen stabil.",
    strategie: "Einstieg erst nach Bestätigung: grüne Folgekerze über dem Hammer-Hoch. Stop unter das Tief der Lunte, Ziel: nächster Widerstand oder MA20.",
    wirkung: "2–3",
    staerke: 4,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="8" y2="42" stroke="#484f58" strokeWidth="1.5"/><rect x="8" y="16" width="12" height="8" fill="#3fb950" stroke="#238636" strokeWidth="0.5" rx="1.5"/></svg>,
  },
  {
    name: "Hanging Man",
    deName: "Hängender Mann",
    merk: "Abverkauf zeigt Schwäche – Käufer werden schwach.",
    color: "red",
    typ: "Bearish Reversal",
    markt: "Aufwärtstrend",
    erklaerung: "Hanging Man zeigt Schwäche im Aufwärtstrend. Lange Lunte = intraday Abverkauf. Erst mit roter Folgekerze als Top verlässlicher.",
    psychologie: "Käufer erschöpft, Smart Money verkauft in Stärke.",
    intraday: "Nach einem Aufwärtsmove treiben Käufer den Kurs zunächst höher. Im Verlauf kommt es zu einem deutlichen Abverkauf nach unten, der nur teilweise zurückgekauft wird.",
    beschreibung: "Wie Hammer, aber nach Aufwärtstrend.",
    bedeutung: "Verkäufer übernehmen – Topbildung möglich.",
    bestaetigung: "Rote Folgekerze, Volumenanstieg, RSI fällt.",
    strategie: "Swing-Trader warten auf eine rote Bestätigungskerze unterhalb des Hanging-Man-Körpers. Stop über dem Hoch, Ziel: nächster Support oder MA20.",
    wirkung: "2",
    staerke: 5,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="8" y2="42" stroke="#484f58" strokeWidth="1.5"/><rect x="8" y="12" width="12" height="8" fill="#f85149" stroke="#da3633" strokeWidth="0.5" rx="1.5"/></svg>,
  },
  {
    name: "Dragonfly Doji",
    deName: "Libellen-Doji",
    merk: "Abverkauf neutralisiert – Entscheidung folgt.",
    color: "green",
    typ: "Bullish Reversal",
    markt: "Abwärtstrend",
    erklaerung: "Der Dragonfly Doji zeigt nach einem Abwärtstrend eine starke Reaktion der Käufer. Starker Rückkauf bis zum Schluss = bullische Stärke.",
    psychologie: "Verkäufer verlieren Momentum, Käufer übernehmen.",
    intraday: "Zu Beginn dominieren Verkäufer und drücken den Kurs deutlich nach unten. Im weiteren Verlauf steigen Käufer massiv ein und bringen den Schlusskurs in die Nähe des Hochs.",
    beschreibung: "Kein oder sehr kleiner Körper, langer unterer Schatten.",
    bedeutung: "Bodenbildung möglich – Käufer verteidigen Support.",
    bestaetigung: "Grüne Folgekerze über Hoch des Doji, RSI dreht nach oben.",
    strategie: "Long-Einstieg nur bei klarer bullischer Folgekerze, die das Hoch des Doji überbietet. Stop knapp unter dem Tief der Lunte.",
    wirkung: "2–3",
    staerke: 3,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="14" y2="42" stroke="#484f58" strokeWidth="1.5"/><line x1="9" x2="19" y1="14" y2="14" stroke="#7d8590" strokeWidth="2.5"/></svg>,
  },
  {
    name: "Gravestone Doji",
    deName: "Grabstein-Doji",
    merk: "Hoch wird komplett verkauft – Warnsignal.",
    color: "red",
    typ: "Bearish Reversal",
    markt: "Aufwärtstrend",
    erklaerung: "Am Ende eines Aufwärtstrends häufig: Käufer treiben den Kurs hoch, Verkäufer drücken ihn bis zum Schluss zurück – Zeichen für Erschöpfung der Bullen.",
    psychologie: "Käufer verlieren Kontrolle, Verkäufer übernehmen.",
    intraday: "Käufer eröffnen stark und treiben den Kurs deutlich nach oben. Später übernehmen Verkäufer komplett und drücken den Schlusskurs zurück zum Eröffnungsniveau.",
    beschreibung: "Kein oder sehr kleiner Körper, langer oberer Schatten.",
    bedeutung: "Topbildung – mögliche Umkehr.",
    bestaetigung: "Rote Folgekerze unterhalb des Doji, Volumenanstieg, Stochastik fällt.",
    strategie: "Short-Einstieg nach roter Bestätigungskerze, die unterhalb des Doji-Körpers schließt. Stop über dem Hoch des Doji.",
    wirkung: "2–3",
    staerke: 4,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="7" y2="32" stroke="#484f58" strokeWidth="1.5"/><line x1="9" x2="19" y1="32" y2="32" stroke="#7d8590" strokeWidth="2.5"/></svg>,
  },
  {
    name: "Inverted Hammer",
    deName: "Invertierter Hammer",
    merk: "Hoch wird getestet – Käufer zeigen erste Stärke.",
    color: "green",
    typ: "Bullish Reversal (schwach)",
    markt: "Abwärtstrend",
    erklaerung: "Käufer zeigen erste Stärke – intraday hochgekauft, Schluss noch tief. Mit Folgekerze bestätigen lassen.",
    psychologie: "Verkäufer verlieren Druck; Käufer testen Widerstand.",
    intraday: "Im Abwärtstrend drücken Verkäufer den Kurs zunächst tiefer. Käufer schaffen intraday eine deutliche Erholung nach oben, können das Niveau aber nicht halten.",
    beschreibung: "Kleiner Körper unten, langer oberer Schatten.",
    bedeutung: "Erste bullische Gegenwehr.",
    bestaetigung: "Grüne Folgekerze über Hoch des Inverted Hammer.",
    strategie: "Sehr konservativ: nur nach klarer grüner Bestätigungskerze über dem Hoch einsteigen. Stop unter dem Tief der Kerze.",
    wirkung: "2–3",
    staerke: 4,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="6" y2="30" stroke="#484f58" strokeWidth="1.5"/><rect x="8" y="30" width="12" height="8" fill="#3fb950" stroke="#238636" strokeWidth="0.5" rx="1.5"/></svg>,
  },
  {
    name: "Shooting Star",
    deName: "Sternschnuppe",
    merk: "Hoch wird verkauft – Käufer erschöpft.",
    color: "red",
    typ: "Bearish Reversal",
    markt: "Aufwärtstrend",
    erklaerung: "Aufwärtsmomentum lässt nach: Hoch ausgenutzt, danach deutlicher Abverkauf innerhalb der Kerze.",
    psychologie: "Käufer erschöpft, Smart Money verkauft in Stärke.",
    intraday: "Käufer treiben den Kurs nach oben auf ein neues Hoch. Danach übernehmen Verkäufer und drücken den Schlusskurs in die Nähe des Tagestiefs.",
    beschreibung: "Kleiner Körper unten, langer oberer Schatten.",
    bedeutung: "Topbildung – potenzielle Umkehr.",
    bestaetigung: "Rote Folgekerze unterhalb des Shooting Star mit Volumenanstieg.",
    strategie: "Short-Einstieg nach roter Bestätigungskerze unterhalb des Kerzenkörpers. Stop knapp über dem Hoch.",
    wirkung: "2–3",
    staerke: 5,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="6" y2="36" stroke="#484f58" strokeWidth="1.5"/><rect x="8" y="30" width="12" height="8" fill="#f85149" stroke="#da3633" strokeWidth="0.5" rx="1.5"/></svg>,
  },
  {
    name: "Marubozu (grün)",
    deName: "Marubozu (grün)",
    merk: "Nur Kaufdruck – Trendstärke ohne Pause.",
    color: "green",
    typ: "Bullish Continuation",
    markt: "Aufwärtstrend",
    erklaerung: "Starke Kaufdominanz: keine Schatten – Käufer kontrollieren die gesamte Periode.",
    psychologie: "Bullen dominieren; Momentum/Volumen stark.",
    intraday: "Vom Open bis zum Close dominieren Käufer die gesamte Handelsspanne. Der Kurs läuft fast nur nach oben, ohne nennenswerte Rücksetzer.",
    beschreibung: "Keine Schatten, langer grüner Körper.",
    bedeutung: "Trendfortsetzung wahrscheinlich.",
    bestaetigung: "Weitere grüne Kerze oder hohes Volumen.",
    strategie: "Swing-Trader nutzen kleine Rücksetzer nach einem grünen Marubozu, um prozyklisch long zu gehen. Stop unter der Mitte der Kerze.",
    wirkung: "3–5",
    staerke: 8,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><rect x="8" y="6" width="12" height="36" fill="#3fb950" stroke="#238636" strokeWidth="0.5" rx="1.5"/></svg>,
  },
  {
    name: "Marubozu (rot)",
    deName: "Marubozu (rot)",
    merk: "Nur Verkaufsdruck – Abwärtsdruck ohne Pause.",
    color: "red",
    typ: "Bearish Continuation",
    markt: "Abwärtstrend",
    erklaerung: "Starke Verkaufsdominanz: keine Schatten – Verkäufer kontrollieren die gesamte Periode.",
    psychologie: "Bären dominieren; Käufer ohne Gegenwehr.",
    intraday: "Vom Open bis zum Close dominieren Verkäufer den Markt. Der Kurs fällt nahezu durchgehend, es entstehen kaum Schatten.",
    beschreibung: "Keine Schatten, langer roter Körper.",
    bedeutung: "Abwärtstrend / Korrektur wahrscheinlich.",
    bestaetigung: "Weitere rote Kerze oder Volumenanstieg.",
    strategie: "Swing-Trader suchen nach einem kleinen Pullback nach oben, um Short-Positionen in Trendrichtung zu eröffnen.",
    wirkung: "3–5",
    staerke: 8,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><rect x="8" y="6" width="12" height="36" fill="#f85149" stroke="#da3633" strokeWidth="0.5" rx="1.5"/></svg>,
  },
  {
    name: "Doji",
    deName: "Doji",
    merk: "Unentschlossenheit – Folgekerze entscheidet.",
    color: "gray",
    typ: "Neutral",
    markt: "Trendphase beliebig",
    erklaerung: "Unentschlossenheit: Käufer und Verkäufer gleichen sich aus – häufig Pause/Wechsel, v. a. nach starken Trends.",
    psychologie: "Gleichgewicht – niemand dominiert.",
    intraday: "Innerhalb der Kerze wechseln sich Käufe und Verkäufe ab. Der Kurs pendelt zwischen Hoch und Tief, schließt aber wieder nahe dem Eröffnungsniveau.",
    beschreibung: "Open ≈ Close, Schatten oben und unten.",
    bedeutung: "Unsicherheit oder Trendwechsel.",
    bestaetigung: "Folgekerze bestätigt Richtung.",
    strategie: "Dojis werden im konservativen Swing-Trading meist nicht direkt gehandelt. Erst die Folgekerze entscheidet.",
    wirkung: "1–2",
    staerke: null,
    svg: () => (
      <svg width={24} height={41} viewBox="0 0 28 48">
        <line x1="14" x2="14" y1="6" y2="42" stroke="#484f58" strokeWidth="1.5" />
        <line x1="7" x2="21" y1="24" y2="24" stroke="#7d8590" strokeWidth="2.5" />
      </svg>
    ),
  },
  {
    name: "Spinning Top",
    deName: "Kreisel",
    merk: "Pause im Trend – Kraft sammelt sich.",
    color: "gray",
    typ: "Neutral / Trendpause",
    markt: "Seitwärtsphase oder Trendpause",
    erklaerung: "Gleichgewicht/Unsicherheit – Markt sammelt Kraft. Oft Vorbote einer größeren Bewegung mit steigendem Volumen.",
    psychologie: "Unentschlossenheit; Institutionelle warten.",
    intraday: "Mehrere Impulse nach oben und unten wechseln sich ab. Der kleine Kerzenkörper zeigt, dass weder Käufer noch Verkäufer sich klar durchsetzen.",
    beschreibung: "Kleiner Körper, obere & untere Schatten ähnlich lang.",
    bedeutung: "Trendpause oder Richtungsänderung möglich.",
    bestaetigung: "Bestätigung durch Folgekerze oder Volumenanstieg.",
    strategie: "Spinning Tops werden selten direkt gehandelt. Break nach oben → prozyklisch long; Break nach unten → prozyklisch short.",
    wirkung: "1–2",
    staerke: null,
    svg: () => <svg width={24} height={41} viewBox="0 0 28 48"><line x1="14" x2="14" y1="6" y2="42" stroke="#484f58" strokeWidth="1.5"/><rect x="8" y="18" width="12" height="8" fill="#7d8590" stroke="#6b7280" strokeWidth="0.5" rx="1.5"/></svg>,
  },
];
